# Generated by Django 6.1 on 2026-09-13 05:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution_name', models.CharField(max_length=255)),
                ('degree', models.CharField(choices=[('SMA', 'Sekolah Menengah Atas'), ('MAN', 'Madrasah Aliyah Negeri'), ('D3', 'Diploma 3'), ('D4', 'Diploma 4'), ('S1', 'Strata 1'), ('S2', 'Strata 2'), ('S3', 'Strata 3')], default='S1', max_length=50)),
                ('major', models.CharField(max_length=255)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
